name: 构建并发布多平台可执行文件

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  discussions: write

jobs:
  build-and-release:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        include:
          - os: windows-latest
            output_name: 掘金小册下载器.exe
          - os: macos-latest
            output_name: 掘金小册下载器
          - os: ubuntu-latest
            output_name: 掘金小册下载器

    runs-on: ${{ matrix.os }}
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 设置 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: 缓存 pip 依赖
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: 缓存 PyInstaller
        uses: actions/cache@v3
        with:
          path: ~/.cache/pyinstaller
          key: ${{ runner.os }}-pyinstaller-${{ hashFiles('**/requirements.txt') }}

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: 准备构建环境
        run: |
          if [ -f config.template.yml ]; then
            cp config.template.yml config.yml
            echo "config.yml 创建成功"
          else
            echo "警告: config.template.yml 不存在，将创建空的 config.yml"
            echo "# 默认配置" > config.yml
            echo "app_name: '掘金小册下载器'" >> config.yml
            echo "version: 1.0.0" >> config.yml
          fi

      - name: 更新版本文件
        run: |
          echo ${GITHUB_REF#refs/tags/} > version.txt

      - name: 构建可执行文件
        run: |
          python scripts/build.py

      - name: 创建发布
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/${{ matrix.output_name }}
          name: 发布版本 ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
